version: "3.1"

services:

  app:
    build:
      context: .
      dockerfile: src/MyWeb/Dockerfile
    ports:
      - 80:80

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090

    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    user: "104"